#!/bin/sh
#
# service-vpopmaild-run
# John Simpson <jms1@jms1.net> 2006-03-26
#
# 2012-07-19: adding "setuidgid vpopmail", changing port from 89 to 8900.
#
###############################################################################
#
# Copyright (C) 2006,2012 John Simpson.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/licenses/gpl.txt
#
###############################################################################

PATH="/usr/bin:/bin:/usr/local/bin"

exec 2>&1
exec setuidgid vpopmail env - PATH="/usr/bin:/bin:/usr/local/bin" \
	tcpserver -vHRD 127.0.0.1 8900 ~vpopmail/bin/vpopmaild
