#!/bin/sh
PATH=/usr/bin:/bin
PLIST=`ps ax -o etime,pid,comm --no-heading | grep qmail-smtpd | \
	grep ':[0-9][0-9]:' | awk '{print $2}'`
if [ -n "${PLIST:-}" ]
then
	for p in $PLIST
	do
		echo "# kill -9 $p"
		kill -9 $p
	done
fi
